AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-lambda-demo

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TestLambdaFunction
      CodeUri: hello_world/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: DynamoDb_Testing_TGW
          MY_AWS_REGION: ap-northeast-1   # renamed from AWS_REGION

      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: DynamoDb_Testing_TGW

      Events:
        # API Gateway trigger
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get

        # EventBridge scheduled trigger (every 5 minutes)
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Input: >
              {
                "action": "scan"
              }

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"

  HelloWorldFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: Lambda IAM Role
    Value: !GetAtt HelloWorldFunctionRole.Arn
